# Generated by Django 3.1.5 on 2021-01-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lecturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='lessons',
            field=models.ManyToManyField(through='schedule.Schedule', to='schedule.Exam'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.exam'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
