# Generated by Django 3.1.5 on 2021-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210104_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='consultation_time',
            field=models.DateTimeField(default='2021-01-10'),
        ),
    ]
