# Generated by Django 3.1.5 on 2021-01-12 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_consultation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['name'], 'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['group'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='lecturer',
            field=models.CharField(max_length=50, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='consultation_time',
            field=models.DateTimeField(default='2021-01-10', verbose_name='Время консультации'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.exam', verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_time',
            field=models.DateTimeField(default='2021-01-10', verbose_name='Время экзамена'),
        ),
    ]
